@startuml
'https://plantuml.com/class-diagram

package gdx {
class Game {
}
}

package gdx.graphics.g2d {
class BitmapFont {
}

class SpriteBatch {
}
}

package heslington_hustle.screens {

}

@enduml