@startuml
'https://plantuml.com/class-diagram
/'
we thought that an object component architecture may be good
'/

class Coordinates
class Collider
class Input


class Player
class Building

class Map
class Game

Player o-- Coordinates
Building o-- Coordinates
Player o--


@enduml