@startuml
'https://plantuml.com/class-diagram
package gdx {
class Gdx {
+ {abstract} int : getWidth()
+ {abstract} int : getHeight()
}
}

package graphics.g2d {
class Sprite {
}
class TextureAtlas
}

package game{

class Activity{
    String description;
    float energy;
    float timeUse;
    Rectangle zone;
}

enum ActivityType {
    EAT
    RECREATION
    SLEEP
    STUDY
}
Activity o-- ActivityType

class HeslingtonHustle {
    + {static} float Energy;
    + {static} float hoursLeft;
    + {static} int Day;
    + {static} LocalTime Time;

    +create()
    +changeScreen(int Screen)
}

class Player extends graphics.g2d.Sprite {
- TextureAtlas : textureAtlas
- {static} String : direction
- TiledMapLayer : collisionLayer
+ String : character

+ void : setTexture(String : textureName)
+ boolean : collision(int : transX, int : transY)
+ void : moveUp()
+ void : moveDown()
+ void : moveLeft()
+ void : moveRight()
+ void : stationary()
+ void : dispose()
}
}

package screens{
class CharacterSelectionScreen
class GameScreen
}

textureAtlas --- Player
Gdx --- Player
GameScreen o-- Player
CharacterSelectionScreen "2" o-- Player
@enduml