@startuml
'https://plantuml.com/class-diagram
/'
more detail about the functionality of the classes in the screens package
'/

package com.badlogic.gdx {
class ScreenAdapter
}

package screens {

class ActivityScreen
class CharacterSelectionScreen
class EndGameScreen
class ErrorScreen
class GameScreen
class HowToPlayScreen
class MainMenuScreen
class NewDayScreen
class PauseScreen

ActivityScreen <|-- ScreenAdapter
CharacterSelectionScreen <|-- ScreenAdapter
EndGameScreen <|-- ScreenAdapter
ErrorScreen <|-- ScreenAdapter
GameScreen <|-- ScreenAdapter
HowToPlayScreen <|-- ScreenAdapter
MainMenuScreen <|-- ScreenAdapter
NewDayScreen <|-- ScreenAdapter
PauseScreen <|-- ScreenAdapter
}
}


@enduml