@startuml
skinparam linetype ortho

class ActivityScreen {
  + ActivityScreen(HeslingtonHustle, Activity): 
  - stage: Stage
  ~ font: BitmapFont
  ~ activity: Activity
  - game: HeslingtonHustle
  ~ skin: Skin
  - batch: SpriteBatch
  + resize(int, int): void
  + show(): void
  + render(float): void
  + hide(): void
  + dispose(): void
}
class CharacterSelectionScreen {
  + CharacterSelectionScreen(HeslingtonHustle): 
  - stage: Stage
  ~ skin: Skin
  - game: HeslingtonHustle
  + resize(int, int): void
  + dispose(): void
  + hide(): void
  + show(): void
  + render(float): void
}
class EndGameScreen {
  + EndGameScreen(HeslingtonHustle): 
  ~ game: HeslingtonHustle
  - stage: Stage
  ~ skin: Skin
  ~ font: BitmapFont
  + resize(int, int): void
  + show(): void
  + hide(): void
  + render(float): void
  + dispose(): void
}
class ErrorScreen {
  + ErrorScreen(HeslingtonHustle, String): 
  ~ font: BitmapFont
  - batch: SpriteBatch
  - stage: Stage
  - game: HeslingtonHustle
  ~ skin: Skin
  ~ errorType: String
  + show(): void
  + render(float): void
  + dispose(): void
  + resize(int, int): void
  + hide(): void
}
class GameScreen {
  + GameScreen(HeslingtonHustle): 
  ~ eat: Activity
  ~ orange: Texture
  ~ atlas: TextureAtlas
  ~ font: BitmapFont
  ~ map: TiledMap
  ~ blank: Texture
  ~ study: Activity
  ~ batch: SpriteBatch
  ~ player: Player
  ~ overviewCam: OrthographicCamera
  ~ game: HeslingtonHustle
  ~ renderer: OrthogonalTiledMapRenderer
  ~ recreation: Activity
  ~ sleep: Activity
  + render(float): void
  + dispose(): void
  + resume(): void
  + resize(int, int): void
}
enum GameState << enumeration >> {
  + GameState(): 
  + ACTIVITY: 
  + MENU: 
  + FREE_ROAM: 
  + END: 
  + valueOf(String): GameState
  + values(): GameState[]
}
class HeslingtonHustle {
  + HeslingtonHustle(): 
  + font: BitmapFont
  + END: int
  + PAUSE: int
  + Time: LocalTime
  ~ pauseScreen: PauseScreen
  ~ howToPlayScreen: HowToPlayScreen
  + NEWDAY: int
  ~ endScreen: EndGameScreen
  + GAME: int
  + CHARACTER: int
  + Energy: float
  + Day: int
  + MENU: int
  + batch: SpriteBatch
  ~ gameScreen: GameScreen
  + hoursLeft: float
  ~ menuScreen: MainMenuScreen
  + stats: Stats
  + HOWTOPLAY: int
  ~ newDayScreen: NewDayScreen
  ~ state: GameState
  ~ characterScreen: CharacterSelectionScreen
  + create(): void
  + dispose(): void
  + setState(GameState): void
  + render(): void
  + getState(): GameState
  + changeScreen(int): void
  + reset(): void
  + resize(int, int): void
  + resume(): void
  + pause(): void
}
class HowToPlayScreen {
  + HowToPlayScreen(HeslingtonHustle): 
  - stage: Stage
  ~ skin: Skin
  ~ batch: SpriteBatch
  - game: HeslingtonHustle
  ~ font: BitmapFont
  + show(): void
  + hide(): void
  + render(float): void
  + resize(int, int): void
  + dispose(): void
}
class MainMenuScreen {
  + MainMenuScreen(HeslingtonHustle): 
  - stage: Stage
  - skin: Skin
  - game: HeslingtonHustle
  + resize(int, int): void
  + hide(): void
  + dispose(): void
  + show(): void
  + render(float): void
}
class NewDayScreen {
  + NewDayScreen(HeslingtonHustle): 
  ~ skin: Skin
  - game: HeslingtonHustle
  - batch: SpriteBatch
  - stage: Stage
  ~ font: BitmapFont
  + dispose(): void
  + hide(): void
  + resize(int, int): void
  + show(): void
  + render(float): void
}
class PauseScreen {
  + PauseScreen(HeslingtonHustle): 
  - stage: Stage
  ~ font: BitmapFont
  - batch: SpriteBatch
  - game: HeslingtonHustle
  + resize(int, int): void
  + show(): void
  + render(float): void
  + hide(): void
}

ActivityScreen            -[#595959,dashed]->  ActivityScreen           
ActivityScreen            -[#595959,dashed]->  EndGameScreen            : "«create»"
ActivityScreen            -[#595959,dashed]->  ErrorScreen              : "«create»"
ActivityScreen           "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
ActivityScreen            -[#595959,dashed]->  NewDayScreen             : "«create»"
CharacterSelectionScreen "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
EndGameScreen             -[#595959,dashed]->  EndGameScreen            
EndGameScreen            "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
ErrorScreen              "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
GameScreen                -[#595959,dashed]->  ActivityScreen           : "«create»"
GameScreen               "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
GameState                 +-[#820000,plain]-  HeslingtonHustle         
HeslingtonHustle          -[#595959,dashed]->  CharacterSelectionScreen : "«create»"
HeslingtonHustle         "1" *-[#595959,plain]-> "characterScreen\n1" CharacterSelectionScreen 
HeslingtonHustle         "1" *-[#595959,plain]-> "endScreen\n1" EndGameScreen            
HeslingtonHustle          -[#595959,dashed]->  EndGameScreen            : "«create»"
HeslingtonHustle         "1" *-[#595959,plain]-> "gameScreen\n1" GameScreen               
HeslingtonHustle          -[#595959,dashed]->  GameScreen               : "«create»"
HeslingtonHustle         "1" *-[#595959,plain]-> "state\n1" GameState                
HeslingtonHustle          -[#595959,dashed]->  HeslingtonHustle         
HeslingtonHustle          -[#595959,dashed]->  HowToPlayScreen          : "«create»"
HeslingtonHustle         "1" *-[#595959,plain]-> "howToPlayScreen\n1" HowToPlayScreen          
HeslingtonHustle         "1" *-[#595959,plain]-> "menuScreen\n1" MainMenuScreen           
HeslingtonHustle          -[#595959,dashed]->  MainMenuScreen           : "«create»"
HeslingtonHustle         "1" *-[#595959,plain]-> "newDayScreen\n1" NewDayScreen             
HeslingtonHustle          -[#595959,dashed]->  NewDayScreen             : "«create»"
HeslingtonHustle          -[#595959,dashed]->  PauseScreen              : "«create»"
HeslingtonHustle         "1" *-[#595959,plain]-> "pauseScreen\n1" PauseScreen              
HowToPlayScreen          "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
MainMenuScreen           "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
NewDayScreen             "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
PauseScreen              "1" *-[#595959,plain]-> "game\n1" HeslingtonHustle         
@enduml
