@startuml
'https://plantuml.com/state-diagram

[*] --> StartMenu

state StartMenu {
    StartMenu: User can select character
}

state Game{
    [*] --> IdleMovement

    IdleMovement: Player can move around the map

    IdleMovement --> StartActivity :Collision with building
    StartActivity --> Interaction
    StartActivity  --> Sleep
    Interaction --> IdleMovement:Activity Finished
    Interaction: Updates energy and time counters
    Sleep:New day
    Sleep --> IdleMovement
    Sleep --> [*]
}

state End{
    End:Calculates and displays the Players score
}

state PauseMenu{

}

StartMenu --> Game: StartGame
Game -> PauseMenu
Game <- PauseMenu
Game --> End
End -> [*]
PauseMenu --> [*] : Quit game
@enduml